vault_win_password: "Student1!Student1!"
$ANSIBLE_VAULT;1.1;AES256
65383638373534663065333630333137363862656662623063363361663433343134306664303365
6236626237383138383330353736383664343237643566300a646363333731373436323131373865
39633964326537613132623837646566613165336336346461373265663864646338326331316334
3331306332333161380a326533376635396533616539376233393139333836343065366462393633
6563
